package eu.biogateway.cytoscape.internal.gui.tutorial;

import javax.swing.*;
import java.awt.*;

public class BGTutorial {
    private final JFrame mainFrame;
    private JPanel rootPanel;
    private JButton nextButton;
    private JButton previousButton;
    private JPanel pagePanel;
    private JPanel headerPanel;
    private JPanel firstPagePanel;

    private JPanel selectDatasetPanel = new BGSelectDatasets();

    public BGTutorial() {

        JFrame frame = new JFrame("Biogateway Query Builder");
        this.mainFrame = frame;

        frame.setPreferredSize(new Dimension(600, 600));
        frame.setContentPane(this.rootPanel);
        frame.pack();
        frame.setLocationRelativeTo(null);
        frame.setVisible(true);

        nextButton.addActionListener(l -> {
            goToDatasetPage();
        });
    }

    private void goToDatasetPage() {
        pagePanel.removeAll();
        pagePanel.add(selectDatasetPanel, BorderLayout.CENTER);
        rootPanel.updateUI();

    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        rootPanel = new JPanel();
        rootPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        rootPanel.add(panel1, BorderLayout.SOUTH);
        nextButton = new JButton();
        nextButton.setText("Next");
        panel1.add(nextButton, BorderLayout.EAST);
        previousButton = new JButton();
        previousButton.setText("Previous");
        panel1.add(previousButton, BorderLayout.WEST);
        pagePanel = new JPanel();
        pagePanel.setLayout(new BorderLayout(0, 0));
        rootPanel.add(pagePanel, BorderLayout.CENTER);
        firstPagePanel = new JPanel();
        firstPagePanel.setLayout(new BorderLayout(0, 0));
        pagePanel.add(firstPagePanel, BorderLayout.CENTER);
        headerPanel = new JPanel();
        headerPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        rootPanel.add(headerPanel, BorderLayout.NORTH);
        final JLabel label1 = new JLabel();
        label1.setText("Intro - Tutorial");
        headerPanel.add(label1);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return rootPanel;
    }
}
