package org.cytoscape.biogwplugin.internal.gui;

import org.cytoscape.application.swing.CytoPanelComponent;
import org.cytoscape.application.swing.CytoPanelName;
import org.cytoscape.biogwplugin.internal.libs.JCheckBoxTree;
import org.cytoscape.biogwplugin.internal.BGServiceManager;


import javax.swing.*;
import javax.swing.border.TitledBorder;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;
import javax.swing.tree.TreePath;
import java.awt.*;

public class BGControlPanel extends JPanel implements CytoPanelComponent {
    private BGServiceManager serviceManager;
    private JPanel mainPanel;
    private JComboBox comboBox1;
    private JPanel treePanel;


    public BGControlPanel(BGServiceManager serviceManager) {
        this.serviceManager = serviceManager;
        this.add(mainPanel);

        setupTreePanel();
    }


    private void setupTreePanel() {
        DefaultTreeModel model = serviceManager.getCache().getAvailableGraphs();
        JCheckBoxTree tree = new JCheckBoxTree(model);
        //tree.expandRow(0);
        tree.setRootVisible(false);
        tree.setShowsRootHandles(true);
        treePanel.add(tree);

        tree.addCheckChangeEventListener(new JCheckBoxTree.CheckChangeEventListener() {
            public void checkStateChanged(JCheckBoxTree.CheckChangeEvent event) {

                serviceManager.getServer().setActiveRelationsForPaths(tree.getCheckedPaths());

/*                System.out.println(event.getSource());
                TreePath path = (TreePath) event.getSource();
                DefaultMutableTreeNode graph = (DefaultMutableTreeNode) path.getParentPath().getLastPathComponent();
                String graphName = (String) graph.getUserObject();
                String relationName = (String) ((DefaultMutableTreeNode) path.getLastPathComponent()).getUserObject();
                Boolean isSelected = tree.isSelectedPartially(path);
                serviceManager.getServer().setActivationForRelationType(graphName, relationName, isSelected);*/
                }
        });
    }



    /*
    System.out.println(event);
                TreePath path = (TreePath) event.getSource();
                System.out.println(path);
                TreePath[] paths = cbt.getCheckedPaths();
                for (TreePath tp : paths) {
                    for (Object pathPart : tp.getPath()) {
                        System.out.print(pathPart + ",");
                    }
                    System.out.println();
                }

     */

   /*
    private void addActionListenerToGraphCheckbox(JCheckBox box, String graph) {
        box.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                if (box.isSelected()) {
                    serviceManager.getServer().addGraphFilter(graph);
                } else {
                    serviceManager.getServer().removeGraphFilter(graph);
                }
            }
        });
    }*/

// CytoPanel implementations:

    @Override
    public Component getComponent() {
        return this;
    }

    @Override
    public CytoPanelName getCytoPanelName() {
        return CytoPanelName.WEST;
    }

    @Override
    public String getTitle() {
        return "BioGateway";
    }

    @Override
    public Icon getIcon() {
        return null;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        mainPanel = new JPanel();
        mainPanel.setLayout(new BorderLayout(0, 0));
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        mainPanel.add(panel1, BorderLayout.NORTH);
        panel1.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Taxon", TitledBorder.DEFAULT_JUSTIFICATION, TitledBorder.DEFAULT_POSITION, null, new Color(-16777216)));
        final JLabel label1 = new JLabel();
        label1.setText("Default Taxon: ");
        panel1.add(label1);
        comboBox1 = new JComboBox();
        final DefaultComboBoxModel defaultComboBoxModel1 = new DefaultComboBoxModel();
        defaultComboBoxModel1.addElement("Homo Sapiens");
        defaultComboBoxModel1.addElement("Mus Musculus");
        defaultComboBoxModel1.addElement("Rattus Norwegicus");
        comboBox1.setModel(defaultComboBoxModel1);
        panel1.add(comboBox1);
        treePanel = new JPanel();
        treePanel.setLayout(new BorderLayout(0, 0));
        mainPanel.add(treePanel, BorderLayout.SOUTH);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        mainPanel.add(panel2, BorderLayout.CENTER);
        panel2.setBorder(BorderFactory.createTitledBorder(BorderFactory.createEtchedBorder(), "Active Graphs"));
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return mainPanel;
    }
}