package org.cytoscape.biogwplugin.internal.gui;

import javax.swing.*;
import java.awt.*;
import java.awt.event.ActionListener;

public class BGQuickSearchResultsView {

    public static final String ACTION_SELECT_NODE = "Choose selected node";

    private final JFrame mainFrame;
    private JPanel panel1;
    private JTable searchResultsTable;
    private JPanel buttonPanel;
    private JButton chooseSelectedButton;
    private ActionListener listener;

    public BGQuickSearchResultsView(ActionListener listener) {
        this.listener = listener;
        JFrame frame = new JFrame("Biogateway Query Builder");
        this.mainFrame = frame;
        frame.setPreferredSize(new Dimension(600, 400));
        frame.setContentPane(this.panel1);
        this.setupUI();
        frame.pack();
        frame.setVisible(true);
    }

    private void setupUI() {
        chooseSelectedButton.setActionCommand(ACTION_SELECT_NODE);
        chooseSelectedButton.addActionListener(listener);
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        searchResultsTable.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    public JTable getSearchResultsTable() {
        return searchResultsTable;
    }

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        buttonPanel = new JPanel();
        buttonPanel.setLayout(new FlowLayout(FlowLayout.CENTER, 5, 5));
        panel1.add(buttonPanel, BorderLayout.SOUTH);
        chooseSelectedButton = new JButton();
        chooseSelectedButton.setText("Choose selected");
        buttonPanel.add(chooseSelectedButton);
        final JScrollPane scrollPane1 = new JScrollPane();
        panel1.add(scrollPane1, BorderLayout.CENTER);
        searchResultsTable = new JTable();
        scrollPane1.setViewportView(searchResultsTable);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
