package org.cytoscape.biogwplugin.internal.gui;

import javax.swing.*;
import java.awt.*;

public class BGRelationSourceView {
    private JPanel panel1;
    private JButton openPubmedURLButton;
    private JTable sourceInformationTable;

    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        panel1.add(panel2, BorderLayout.NORTH);
        openPubmedURLButton = new JButton();
        openPubmedURLButton.setText("Open Pubmed URL");
        panel2.add(openPubmedURLButton, BorderLayout.EAST);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel1.add(panel3, BorderLayout.CENTER);
        sourceInformationTable = new JTable();
        sourceInformationTable.setAutoCreateRowSorter(true);
        sourceInformationTable.setEnabled(true);
        panel3.add(sourceInformationTable, BorderLayout.CENTER);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
