package eu.biogateway.cytoscape.internal.gui;

import javax.swing.*;
import java.awt.*;

public class BGImportExportView {
    private final BGImportExportController controller;
    private JFrame mainFrame;
    private JTabbedPane tabbedPane1;
    private JPanel panel1;
    private JTabbedPane tabbedPane2;
    private JPanel Import;
    private JButton nextButton;
    private JButton importButton;
    private JPanel edgeImportsPanel;
    private JPanel nodeImportsPanel;

    public BGImportExportView(BGImportExportController controller) {
        this.controller = controller;
        mainFrame = new JFrame("BioGateway Import/Export");
        $$$setupUI$$$();
        mainFrame.setPreferredSize(new Dimension(800, 400));
        mainFrame.setContentPane(this.panel1);
        setupActions();
        mainFrame.pack();
        mainFrame.setVisible(true);
    }


    private void setupActions() {
        nextButton.addActionListener(e -> {
            controller.generateConversions();
        });
    }

    public JPanel getEdgeImportsPanel() {
        return edgeImportsPanel;
    }

    public JPanel getNodeImportsPanel() {
        return nodeImportsPanel;
    }

    private void createUIComponents() {
        // TODO: place custom component creation code here
        nodeImportsPanel = new JPanel();
        nodeImportsPanel.setLayout(new BoxLayout(nodeImportsPanel, BoxLayout.Y_AXIS));

        edgeImportsPanel = new JPanel();
        edgeImportsPanel.setLayout(new BoxLayout(edgeImportsPanel, BoxLayout.Y_AXIS));
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        createUIComponents();
        panel1 = new JPanel();
        panel1.setLayout(new BorderLayout(0, 0));
        tabbedPane1 = new JTabbedPane();
        panel1.add(tabbedPane1, BorderLayout.CENTER);
        Import = new JPanel();
        Import.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Import", Import);
        tabbedPane2 = new JTabbedPane();
        Import.add(tabbedPane2, BorderLayout.CENTER);
        final JPanel panel2 = new JPanel();
        panel2.setLayout(new BorderLayout(0, 0));
        tabbedPane2.addTab("Nodes", panel2);
        final JPanel panel3 = new JPanel();
        panel3.setLayout(new BorderLayout(0, 0));
        panel2.add(panel3, BorderLayout.SOUTH);
        nextButton = new JButton();
        nextButton.setText("Next");
        panel3.add(nextButton, BorderLayout.EAST);
        final JScrollPane scrollPane1 = new JScrollPane();
        scrollPane1.setHorizontalScrollBarPolicy(31);
        panel2.add(scrollPane1, BorderLayout.CENTER);
        scrollPane1.setViewportView(nodeImportsPanel);
        final JPanel panel4 = new JPanel();
        panel4.setLayout(new BorderLayout(0, 0));
        tabbedPane2.addTab("Edges", panel4);
        final JPanel panel5 = new JPanel();
        panel5.setLayout(new BorderLayout(0, 0));
        panel4.add(panel5, BorderLayout.SOUTH);
        importButton = new JButton();
        importButton.setText("Import");
        panel5.add(importButton, BorderLayout.EAST);
        panel4.add(edgeImportsPanel, BorderLayout.CENTER);
        final JPanel panel6 = new JPanel();
        panel6.setLayout(new BorderLayout(0, 0));
        tabbedPane1.addTab("Export", panel6);
    }

    /**
     * @noinspection ALL
     */
    public JComponent $$$getRootComponent$$$() {
        return panel1;
    }
}
