package eu.biogateway.cytoscape.internal.gui;

import eu.biogateway.cytoscape.internal.BGServiceManager;
import eu.biogateway.cytoscape.internal.server.BGSettings;

import javax.swing.*;
import java.awt.*;

@SuppressWarnings("FieldCanBeLocal")
public class BGSettingsView {
    private final JFrame mainFrame;
    private final BGSettings settings;
    private JPanel panel2;

    private JCheckBox useBioGatewayVisualStyleCheckBox;
    private JTextField configFileURlField;
    private JButton saveChangesButton;
    private JButton cancelButton;


    public BGSettingsView() {
        this.settings = BGServiceManager.INSTANCE.getDataModelController().getSettings();
        $$$setupUI$$$();
        mainFrame = new JFrame("BioGateway Settings");
        mainFrame.setContentPane(this.panel2);

        loadParameters();
        setupButtons();

        mainFrame.pack();
        mainFrame.setVisible(true);

    }


    private void setupButtons() {
        saveChangesButton.addActionListener(e -> {
            saveParameters();
        });
        cancelButton.addActionListener(e -> {
            loadParameters();
        });
    }

    private void saveParameters() {
        settings.setConfigXMLFileURL(configFileURlField.getText());
        settings.setUseBioGatewayLayoutStyleAsDefault(useBioGatewayVisualStyleCheckBox.isSelected());
        settings.saveParameters();
    }

    private void loadParameters() {
        useBioGatewayVisualStyleCheckBox.setSelected(settings.getUseBioGatewayLayoutStyleAsDefault());
        configFileURlField.setText(settings.getConfigXMLFileURL());
    }


    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new GridBagLayout());
        useBioGatewayVisualStyleCheckBox = new JCheckBox();
        useBioGatewayVisualStyleCheckBox.setText("Use BioGateway visual style as default");
        GridBagConstraints gbc;
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 0;
        gbc.gridwidth = 2;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(useBioGatewayVisualStyleCheckBox, gbc);
        final JLabel label1 = new JLabel();
        label1.setText("Config File URL:");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 1;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        panel1.add(label1, gbc);
        configFileURlField = new JTextField();
        configFileURlField.setColumns(20);
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 1;
        gbc.weightx = 1.0;
        gbc.weighty = 1.0;
        gbc.anchor = GridBagConstraints.WEST;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(configFileURlField, gbc);
        cancelButton = new JButton();
        cancelButton.setText("Cancel");
        gbc = new GridBagConstraints();
        gbc.gridx = 0;
        gbc.gridy = 2;
        gbc.fill = GridBagConstraints.HORIZONTAL;
        panel1.add(cancelButton, gbc);
        saveChangesButton = new JButton();
        saveChangesButton.setText("Save changes");
        gbc = new GridBagConstraints();
        gbc.gridx = 1;
        gbc.gridy = 2;
        gbc.anchor = GridBagConstraints.EAST;
        panel1.add(saveChangesButton, gbc);
    }
}
